data:
 build: data
 volumes:
   - ./datavolume/home:/var/jenkins_home
   - ./datavolume/logs:/var/log/jenkins

master:
  build: master
  volumes_from:
    - data
  ports:
    - "50000:50000"

nginx:
  build: nginx
  ports:
     - "80:80"
  links:
     - master:jenkins-master
